### ISSUE TITLE
SCORE returning NaN when individual is missing both values

### ISSUE THREAD

**Issue by demodw** [sriramlab/SCORE#2]
Hi,

Thanks for releasing this tool. It's really cut down a lot on analysis time for me!

It seems that in the case that when one (or more) individuals are missing both phenotypes, SCORE simply returns NaN for all estimates, rather than just ignoring these individuals completely.

When comparing a lot of phenotypes with different patterns of missingness, it can be quite the task to 1) filter out those that has both missing phenotypes, 2) create a new plink subset of data (since SCORE requires it in the same order as the phenotype file it seems). 

Cheers,
David

**Comment by ariel-wu** [comment]
Hi David, 
Thanks for reaching out. SCORE should handle different missing patterns in phenotypes. Please use "example/pheno_1.missing" as an example. Please note that the software recognizes "NA" and "-9" as missing values. 
There are several reasons that it return NA. For instance, when the true heritability is too low, it may behave so. Could you share an example output?

**Comment by demodw** [comment]
Hi,

You are indeed correct, I had miss-coded the missing values. Thank you for clarifying this! I see you've added an example with missingess, that's great. Thank you!

Br
David
